### ISSUE TITLE
Allow lack of quotes in CSV.write()

### ISSUE THREAD

**Issue by kescobo** [JuliaData/CSV.jl#235]
It would be useful to be able to write delimited files without quoting strings. `CSVFiles` uses `quotechar=nothing`, which seems sensible. I think `pandas` in python uses `False`, but I think `Union{Char, Bool}` makes less sense (because what would happen if `true`?). I think there's a different package that uses an empty `String` (because there's no empty `Char`), but again, is seems weird to do that since you wouldn't want to allow arbitrary strings.

```julia
julia> using DataFrames

julia> using CSV

julia>  df = DataFrame(a=["One","Two"])
2×1 DataFrames.DataFrame
│ Row │ a   │
├─────┼─────┤
│ 1   │ One │
│ 2   │ Two │

julia> CSV.write("test.csv", df, quotechar=false)
ERROR: TypeError: Type: in typeassert, expected Char, got Bool

julia> CSV.write("test.csv", df, quotechar="")
ERROR: TypeError: Type: in typeassert, expected Char, got String

julia> CSV.write("test.csv", df, quotechar=nothing)
ERROR: TypeError: Type: in typeassert, expected Char, got Void
```

**Comment by quinnj** [comment]
I have a change locally that is much smarter about quoting, i.e. it only quotes strings when they actually need escaping. Would that work for your case? I can't imagine there being a scenario where a user still doesn't wanted quoted field even if their string actually needs quoting.

**Comment by kescobo** [comment]
>Would that work for your case?

Probably? But I am concerned by this phrase:

>I can't imagine there being a scenario...

Because I am frequently shocked by what the people I'm collaborating with want or need. Also, MS Excel seems to be able to happily open files that make every other parser break, and all of my collaborators only use Excel (I recently had a file that had carriage returns *inside* a cell... no quotes, no escaping, but Excel was fine).

Is there a major issue with allowing a user to drop quotes, or is it just a matter of principle? If it's a problem for implementation, I get it (though FileIO can handle it), but if it's just because we can't imagine how weird stuff can get, I'd prefer to at least have the option.

**Comment by quinnj** [comment]
This is fixed on master with a rewrite of `CSV.write(source, filename; kwargs...)`; `CSV.write` now quotes fields only when needed (i.e. a delimiter or newline is included). I don't think it's reasonable for the package to allow producing invalid CSV files by dis-allowing quoting entirely, so I'm considering this fixed.

**Comment by kescobo** [comment]
This seems reasonable to me, and will be sufficient for at least 95% of my use cases. And for the other 5%, there's always `sed` 😆

**Comment by bjarthur** [comment]
the OP's example is still broken when `header=false` is supplied.

**Comment by bjarthur** [comment]
nevermind!  its `writeheader` not `header` !!
